[package]
name = "closed01"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
license = "MIT"
repository = "https://github.com/mneumann/closed01-rs"
description = "Provides checked floating point operations within the range [0,1]"
keywords = ["math"]

[dependencies]

rand = "0.3"
